name: CI
on:
  pull_request:
  push:

jobs:
  build-and-archive:
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v3

        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.2'

        - name: workspace-settings-overrides
          run: echo ${{ secrets.XCCONFIG }} | base64 --decode > ./Configs/workspace-settings-overrides.xcconfig

        - name: build
          run: |
            xcodebuild build -allowProvisioningUpdates -configuration Release -scheme ZitiPacketTunnel -arch x86_64 -arch arm64 ONLY_ACTIVE_ARCH=NO -sdk macosx
            xcodebuild build -allowProvisioningUpdates -configuration Release -scheme ZitiMobilePacketTunnel -arch arm64 -sdk iphoneos

        - name: archive
          run: |
            xcodebuild archive -allowProvisioningUpdates -configuration Release -scheme ZitiPacketTunnel -arch x86_64 -arch arm64 ONLY_ACTIVE_ARCH=NO -sdk macosx -archivePath ./ZitiPacketTunnel.xarchive
            xcodebuild archive -allowProvisioningUpdates -configuration Release -scheme ZitiMobilePacketTunnel -arch arm64 -sdk iphoneos -archivePath ./ZitiMobilePacketTunnel.xarchive
