name: CI
on:
  pull_request:
  push:

jobs:
  build-and-archive:
    runs-on: macos-latest

    steps:
        - uses: actions/checkout@v3

        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.2'

        - name: workspace-settings-overrides
          run: echo ${{ secrets.XCCONFIG }} | base64 --decode > ./Configs/workspace-settings-overrides.xcconfig

        - name: Create XArchive
          env:
            SCHEME: 'ZitiPacketTunnel'
            ARCH_FLAGS: ''
            SDK: 'macosx'
            ARCHIVE_PATH: './ZitiPacketTunnel.xarchive'
            AUTH_KEY: ${{ secrets.APPLE_DEVELOPER_KEY }}
            AUTH_KEY_ID: ${{ secrets.APPLE_DEVELOPER_KEY_ID }}
            AUTH_KEY_ISSUER_ID: ${{ secrets.APPLE_DEVELOPER_KEY_ISSUER_ID }}
          run: |
            echo ${AUTH_KEY} | base64 --decode > ./auth.p8
            xcodebuild archive -allowProvisioningUpdates -authenticationKeyPath ${PWD}/auth.p8 -authenticationKeyID ${AUTH_KEY_ID} -authenticationKeyIssuerID ${AUTH_KEY_ISSUER_ID} -configuration Release -scheme ${SCHEME} ${ARCH_FLAGS} -sdk ${SDK} -destination 'generic/platform=macOS' -archivePath ${ARCHIVE_PATH}
