name: CI
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        spec:
        - { scheme: 'ZitiPacketTunnel', sdk: 'macosx', destination: 'generic/platform=macOS'}

    steps:
        - uses: actions/checkout@v3

        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '14.2'

        - name: workspace-settings-overrides
          run: echo ${{ secrets.XCCONFIG }} | base64 --decode > ./Configs/workspace-settings-overrides.xcconfig

        - name: ${{ matrix.spec.scheme }} XArchive
          env:
            SCHEME: ${{ matrix.spec.scheme }}
            SDK: ${{ matrix.spec.sdk }}
            DESTINATION: ${{ matrix.spec.destination }}
            AUTH_KEY: ${{ secrets.APPLE_DEVELOPER_KEY }}
            AUTH_KEY_ID: ${{ secrets.APPLE_DEVELOPER_KEY_ID }}
            AUTH_KEY_ISSUER_ID: ${{ secrets.APPLE_DEVELOPER_KEY_ISSUER_ID }}
          run: |
            echo ${AUTH_KEY} | base64 --decode > ./auth.p8
            xcodebuild archive -allowProvisioningUpdates -authenticationKeyPath ${PWD}/auth.p8 -authenticationKeyID ${AUTH_KEY_ID} -authenticationKeyIssuerID ${AUTH_KEY_ISSUER_ID} -configuration Release -scheme ${SCHEME} -sdk ${SDK} -destination 'generic/platform=macOS' -archivePath ./${SCHEME}.xarchive
